export {default as Homepage} from "./Homepage";
export {default as Login} from "./Login"
export {default as Profile} from "./Profile"
export {default as Register} from "./Register"
export {default as AllProducts} from "./AllProducts"
export {default as Cart} from "./Cart"
export {default as Checkout} from "./Checkout"
export {default as Header} from "./Header"
export {default as Logout} from "./Logout"
export {default as Navbar} from "./Navbar"
export {default as OrderHistory} from "./OrderHistory"
export {default as PaymentScreen} from "./PaymentScreen"
export {default as SingleProduct} from "./SingleProduct"
export {default as SingleArtist} from "./SingleArtist"
export {default as Artists} from "./Artists"
export {default as Search} from "./Search"
export {default as RemoveFromCart} from "./RemoveFromCart"
export {default as Admin} from "./Admin"
export {default as Filterbar} from "./Filterbar"
export {default as DeleteVinyl} from "./DeleteVinyl"
export {default as ChangeQuantity} from "./ChangeQuantity"

export {default as VinylPage} from "./VinylPage"

export {default as AddTag} from "./AddTag"
export {default as RemoveTag} from "./RemoveTag"
export {default as ChangeUserAdmin} from "./ChangeUserAdmin"
export {default as DeleteUser} from "./DeleteUser"
